/*
 * Copyright (c) 2018-present, easy-4-java (https://github.com/easy-4-java).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.pac4j.ext.otp;

import java.io.Serializable;

/**
 * Marker base type for one-time password (OTP) credentials exchanged with a
 * pac4j authentication flow.
 *
 * <p>The class captures the raw response supplied by the end user (typically a
 * six-digit code generated by a hardware token or authenticator app) and is
 * intended to be wrapped by more concrete credential types defined in
 * downstream modules.</p>
 *
 * <p>Instances are immutable: the protected constructor accepts the raw
 * response once at creation time and stores nothing in this marker base
 * class &mdash; subclasses are expected to retain the value through their own
 * private fields.</p>
 *
 * @param rawResponse the raw user-supplied response string; may be
 *                    {@code null} when the credential is constructed lazily
 *                    by the framework.
 *
 * @author easy-4-java contributors
 * @since 3.0.0
 * @see Serializable
 */
@SuppressWarnings("serial")
public class OTPToken implements Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * Protected constructor invoked by subclasses.
     *
     * @param rawResponse the raw user-supplied response; never exposed outside
     *                    the class hierarchy but stored so subclasses can
     *                    persist or re-emit the value.
     */
    protected OTPToken(String rawResponse) {
        // Marker base type — no field is held here on purpose. Subclasses
        // (e.g. TOTP/credential implementations in downstream modules)
        // capture the raw response.
    }
}
